### PR TITLE
update to latest ignite

### PR DESCRIPTION
**Pull request by dholbach**
Update to [latest ignite release](https://github.com/weaveworks/ignite/releases/v0.7.0).

### CODE REVIEW

**Comment by chanwit** [comment]
LGTM

**Comment by stealthybox** [comment]
@dholbach @chanwit This updates the default backend from docker to containerd+CNI.
I don't believe firekube currently installs CNI for you.

**Comment by dholbach** [comment]
After I've ran `./setup.sh` from current `master`, I see this up and running:

```
daemonset.apps/weave-net
```

So I really think we're good.

**Comment by stealthybox** [comment]
> After I've ran `./setup.sh` from current `master`, I see this up and running:
> 
> ```
> daemonset.apps/weave-net
> ```

This is unrelated to the CNI installed within the cluster.

Ignite v0.5.x uses docker and docker's networking to setup the MicroVM's.
In ignite v0.6.x and v0.7.x, the default behavior is changed to use Containerd and CNI for setting up the VM's.

Firekube's installation scripts install many components for the user.
Since CNI is now a dependency for starting ignite VM's, the `setup.sh` needs to install CNI plugins on Linux hosts.

**Pull request merged**
